import { Injectable } from '@angular/core';
import { Http/*, Response*/ } from '@angular/http';
import { AngularFire } from "angularfire2";
import { Events } from 'ionic-angular';
import { Storage } from '@ionic/storage';
//import { Observable } from 'rxjs/Observable';
//import 'rxjs';

@Injectable()

export class UserSettings {

	favoriteTeams = [];

	favoriteLeagues = [
		{
			"id_league": "reg-pref",
			"name": "Regional Preferente"
		}

	];

	constructor(
		private http: Http,
		private events: Events,
		private af: AngularFire,
		private storage: Storage) { }

	favoriteTeam(team) {
		this.storage.set(team.id, JSON.stringify(team)).then(() => this.events.publish('favorites:changed'));
	}

	unFavoriteTeam(team) {
		this.storage.remove(team.id).then(() => this.events.publish('favorites:changed'));
	}

	isFavouriteTeam(teamId) {
		return this.storage.get(teamId).then(value => value ? true : false);
	}

	getFavoriteTeams() {
		let item = [];
		this.storage.forEach((value, key) => {
			item.push(JSON.parse(value))
		});
		return item;
	}

	getFavoriteLeagues() {
		return this.favoriteLeagues;
	}

	getLeagueData(){
		return {
			"name": "Regional Preferente",
			"category": "Regional",
			"teams": [
				{
					"name": "U.D. Las Palmas",
					"id_team": "udlp@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.D. Faycán",
					"id_team": "cdfaycan@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.E.F. Puertos Las Palmas",
					"id_team": "cefpuertoslp@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "A.D. Claret",
					"id_team": "adclaret@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"id_team": "adhuracan@reg-pref",
					"name": "A.D. Huracán",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "Acodetti C.F.",
					"id_team": "acodetticf@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "U.D. Telde",
					"id_team": "udtelde@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.F. Unión Viera",
					"id_team": "cfunionviera@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.D. Arguineguín",
					"id_team": "cdarguineguín@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.D. Doramas",
					"id_team": "cddoramas@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "Arucas C.F.",
					"id_team": "arucascf@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.D. Maspalomas",
					"id_team": "cdmaspalomas@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "R.C. Victoria",
					"id_team": "rcvictoria@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "U.D. Teror",
					"id_team": "udteror@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "U.D. Valsequillo",
					"id_team": "udvalsequillo@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				},
				{
					"name": "C.D. Carnevali",
					"id_team": "cdcarnevali@reg-pref",
					"category": "Regional",
					"label": "",
					"league": {
						"id_league": "reg-pref",
						"name": "Regional Preferente"
					}
				}
			],
			"games": [
				{
					"id_game": 381892593,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 2,
					"guestGoals": 5,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 565078897,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 0,
					"guestGoals": 2,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 357997282,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 2,
					"guestGoals": 5,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 782221776,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 6,
					"guestGoals": 3,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 461847078,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 834677526,
					"fixture": 1,
					"date": "16/9/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 133810213,
					"fixture": 1,
					"date": "17/9/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 3,
					"guestGoals": 3,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 424568521,
					"fixture": 1,
					"date": "18/9/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 4,
					"guestGoals": 2,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 484835774,
					"fixture": 2,
					"date": "27/9/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 4,
					"guestGoals": 3,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 200322026,
					"fixture": 2,
					"date": "23/9/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 0,
					"guestGoals": 4,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 75660010,
					"fixture": 2,
					"date": "23/9/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 3,
					"guestGoals": 0,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 576596075,
					"fixture": 2,
					"date": "23/9/2016",
					"time": "20:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 3,
					"guestGoals": 5,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 738501130,
					"fixture": 2,
					"date": "23/9/2016",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 2,
					"guestGoals": 3,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 629943542,
					"fixture": 2,
					"date": "23/9/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 3,
					"guestGoals": 4,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 562543046,
					"fixture": 2,
					"date": "24/9/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 3,
					"guestGoals": 6,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 674366146,
					"fixture": 2,
					"date": "25/9/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 6,
					"guestGoals": 5,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 14720791,
					"fixture": 3,
					"date": "30/9/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 0,
					"guestGoals": 4,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 962926983,
					"fixture": 3,
					"date": "30/9/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 5,
					"guestGoals": 5,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 605279339,
					"fixture": 3,
					"date": "30/9/2016",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 537085225,
					"fixture": 3,
					"date": "30/9/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 3,
					"guestGoals": 3,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 46990956,
					"fixture": 3,
					"date": "30/9/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 2,
					"guestGoals": 1,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 565828675,
					"fixture": 3,
					"date": "1/10/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 1,
					"guestGoals": 0,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 464685160,
					"fixture": 3,
					"date": "2/10/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 5,
					"guestGoals": 5,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 877394084,
					"fixture": 3,
					"date": "2/10/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 3,
					"guestGoals": 2,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 138717192,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 857419515,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 4,
					"guestGoals": 1,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 239119066,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 2,
					"guestGoals": 5,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 753050549,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 5,
					"guestGoals": 6,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 672811085,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 1,
					"guestGoals": 4,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 472852801,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 3,
					"guestGoals": 6,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 579629481,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 4,
					"guestGoals": 4,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 377550049,
					"fixture": 4,
					"date": "7/10/2016",
					"time": "20:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 3,
					"guestGoals": 5,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 168815718,
					"fixture": 5,
					"date": "14/10/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 0,
					"guestGoals": 4,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 33253800,
					"fixture": 5,
					"date": "14/10/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 1,
					"guestGoals": 3,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 742332558,
					"fixture": 5,
					"date": "14/10/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 1,
					"guestGoals": 2,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 385293370,
					"fixture": 5,
					"date": "14/10/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 4,
					"guestGoals": 5,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 27687045,
					"fixture": 5,
					"date": "14/10/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 232786185,
					"fixture": 5,
					"date": "15/10/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 1,
					"guestGoals": 0,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 911536519,
					"fixture": 5,
					"date": "16/10/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 1,
					"guestGoals": 3,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 524734534,
					"fixture": 5,
					"date": "16/10/2016",
					"time": "12:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 1,
					"guestGoals": 5,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 537575525,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 1,
					"guestGoals": 3,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 719573730,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 560406562,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 1,
					"guestGoals": 5,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 586105306,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 1,
					"guestGoals": 5,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 418002107,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "20:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 5,
					"guestGoals": 1,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 754861715,
					"fixture": 6,
					"date": "21/10/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 3,
					"guestGoals": 3,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 625419835,
					"fixture": 6,
					"date": "22/10/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 0,
					"guestGoals": 6,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 284218045,
					"fixture": 6,
					"date": "23/10/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 1,
					"guestGoals": 1,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 578919913,
					"fixture": 7,
					"date": "31/10/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 93784216,
					"fixture": 7,
					"date": "28/10/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 53209489,
					"fixture": 7,
					"date": "28/10/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 989089116,
					"fixture": 7,
					"date": "28/10/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 0,
					"guestGoals": 0,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 770751860,
					"fixture": 7,
					"date": "28/10/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 1,
					"guestGoals": 0,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 676939564,
					"fixture": 7,
					"date": "28/10/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 2,
					"guestGoals": 1,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 106424159,
					"fixture": 7,
					"date": "29/10/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 5,
					"guestGoals": 6,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 463987725,
					"fixture": 7,
					"date": "30/10/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 5,
					"guestGoals": 0,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 670546639,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 6,
					"guestGoals": 3,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 582450532,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 1,
					"guestGoals": 2,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 76403026,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "20:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 954460714,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 3,
					"guestGoals": 0,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 213567445,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 3,
					"guestGoals": 5,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 488947767,
					"fixture": 8,
					"date": "4/11/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 6,
					"guestGoals": 0,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 200402883,
					"fixture": 8,
					"date": "5/11/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 546980394,
					"fixture": 8,
					"date": "21/12/2016",
					"time": "20:30",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 6,
					"guestGoals": 1,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 392578249,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 4,
					"guestGoals": 1,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 249466610,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 5,
					"guestGoals": 5,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 327587188,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 5,
					"guestGoals": 6,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 144119245,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 4,
					"guestGoals": 2,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 181234449,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 3,
					"guestGoals": 1,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 99067311,
					"fixture": 9,
					"date": "11/11/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 0,
					"guestGoals": 0,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 886414930,
					"fixture": 9,
					"date": "12/11/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 1,
					"guestGoals": 1,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 664958557,
					"fixture": 9,
					"date": "13/11/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 2,
					"guestGoals": 6,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 612754274,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 284939990,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 815075840,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 753054848,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "20:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 6,
					"guestGoals": 5,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 781286523,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 2,
					"guestGoals": 1,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 417956625,
					"fixture": 10,
					"date": "18/11/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 6,
					"guestGoals": 0,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 28213701,
					"fixture": 10,
					"date": "19/11/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 0,
					"guestGoals": 3,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 515000354,
					"fixture": 10,
					"date": "20/11/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 5,
					"guestGoals": 0,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 575378019,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 1,
					"guestGoals": 6,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 438072795,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 5,
					"guestGoals": 0,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 494164478,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 0,
					"guestGoals": 6,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 889442952,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 773987926,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 3,
					"guestGoals": 5,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 309390190,
					"fixture": 11,
					"date": "25/11/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 4,
					"guestGoals": 6,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 637927362,
					"fixture": 11,
					"date": "26/11/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 0,
					"guestGoals": 0,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 624733976,
					"fixture": 11,
					"date": "27/11/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 5,
					"guestGoals": 0,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 547151907,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 5,
					"guestGoals": 5,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 219058489,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 5,
					"guestGoals": 4,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 433587855,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 1,
					"guestGoals": 1,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 364726277,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 3,
					"guestGoals": 0,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 894045577,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 3,
					"guestGoals": 2,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 206327224,
					"fixture": 12,
					"date": "2/12/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 327008424,
					"fixture": 12,
					"date": "3/12/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 5,
					"guestGoals": 5,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 331552651,
					"fixture": 12,
					"date": "4/12/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 2,
					"guestGoals": 1,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 252668534,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 0,
					"guestGoals": 6,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 570172255,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 6,
					"guestGoals": 4,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 660934820,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 4,
					"guestGoals": 4,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 497254705,
					"fixture": 13,
					"date": "10/12/2016",
					"time": "16:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 4,
					"guestGoals": 1,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 421397621,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 3,
					"guestGoals": 3,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 559712141,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "20:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 4,
					"guestGoals": 2,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 545952902,
					"fixture": 13,
					"date": "9/12/2016",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 0,
					"guestGoals": 2,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 329595841,
					"fixture": 13,
					"date": "11/12/2016",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 6,
					"guestGoals": 5,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 991501738,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 3,
					"guestGoals": 2,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 124344368,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 6,
					"guestGoals": 1,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 610539876,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 3,
					"guestGoals": 4,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 474523776,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 2,
					"guestGoals": 0,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 212363757,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 2,
					"guestGoals": 0,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 357688092,
					"fixture": 14,
					"date": "16/12/2016",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 1,
					"guestGoals": 1,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 318087753,
					"fixture": 14,
					"date": "17/12/2016",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 3,
					"guestGoals": 5,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 593603730,
					"fixture": 14,
					"date": "18/12/2016",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 2,
					"guestGoals": 0,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 560205324,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "16:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 3,
					"guestGoals": 6,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 898631316,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "18:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 5,
					"guestGoals": 6,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 879853185,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "19:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 105525884,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "19:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 2,
					"guestGoals": 6,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 749607453,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "19:00",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 5,
					"guestGoals": 0,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 180298495,
					"fixture": 15,
					"date": "7/1/2017",
					"time": "20:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 0,
					"guestGoals": 3,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 767871272,
					"fixture": 15,
					"date": "8/1/2017",
					"time": "20:00",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 5,
					"guestGoals": 2,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 690520345,
					"fixture": 15,
					"date": "8/1/2017",
					"time": "12:20",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 420326379,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 1,
					"guestGoals": 2,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 80157629,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 271215899,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 6,
					"guestGoals": 3,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 607031969,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "20:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 1,
					"guestGoals": 2,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 131979804,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 2,
					"guestGoals": 2,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 82566655,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 4,
					"guestGoals": 6,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 760383503,
					"fixture": 16,
					"date": "13/1/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 6,
					"guestGoals": 3,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 741565297,
					"fixture": 16,
					"date": "15/1/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 6,
					"guestGoals": 5,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 877548611,
					"fixture": 17,
					"date": "20/1/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 0,
					"guestGoals": 4,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 347314935,
					"fixture": 17,
					"date": "19/1/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 0,
					"guestGoals": 6,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 88677857,
					"fixture": 17,
					"date": "19/1/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 3,
					"guestGoals": 4,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 230003996,
					"fixture": 17,
					"date": "20/1/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 552390878,
					"fixture": 17,
					"date": "20/1/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 5,
					"guestGoals": 3,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 287621196,
					"fixture": 17,
					"date": "20/1/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 5,
					"guestGoals": 1,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 334156777,
					"fixture": 17,
					"date": "21/1/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 4,
					"guestGoals": 6,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 987711524,
					"fixture": 17,
					"date": "22/1/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 4,
					"guestGoals": 6,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 474286040,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 53379431,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "20:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 949967975,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 6,
					"guestGoals": 5,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 693590659,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 714868288,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 3,
					"guestGoals": 4,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 794120262,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 517401680,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 0,
					"guestGoals": 5,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 222121732,
					"fixture": 18,
					"date": "27/1/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 4,
					"guestGoals": 5,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 78286722,
					"fixture": 19,
					"date": "3/2/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 2,
					"guestGoals": 5,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 791254801,
					"fixture": 19,
					"date": "3/2/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 1,
					"guestGoals": 5,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 222249953,
					"fixture": 19,
					"date": "3/2/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 2,
					"guestGoals": 2,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 117731711,
					"fixture": 19,
					"date": "3/2/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 5,
					"guestGoals": 1,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 756848430,
					"fixture": 19,
					"date": "3/2/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 1,
					"guestGoals": 4,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 982852266,
					"fixture": 19,
					"date": "4/2/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 992036706,
					"fixture": 19,
					"date": "5/2/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 268857881,
					"fixture": 19,
					"date": "5/2/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 0,
					"guestGoals": 2,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 723652481,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 4,
					"guestGoals": 1,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 94570103,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 1,
					"guestGoals": 2,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 322776493,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 5,
					"guestGoals": 6,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 998338282,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": 1,
					"guestGoals": 6,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 182941680,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 2,
					"guestGoals": 4,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 145916475,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 6,
					"guestGoals": 1,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 831771003,
					"fixture": 20,
					"date": "10/2/2017",
					"time": "20:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 4,
					"guestGoals": 0,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 89625950,
					"fixture": 20,
					"date": "12/2/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 1,
					"guestGoals": 6,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 694884205,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": 3,
					"guestGoals": 4,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 168252775,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": 6,
					"guestGoals": 0,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 921633534,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": 6,
					"guestGoals": 4,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 701576778,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 6,
					"guestGoals": 6,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 214163781,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": 4,
					"guestGoals": 3,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 739408622,
					"fixture": 21,
					"date": "17/2/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": 3,
					"guestGoals": 6,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 480442022,
					"fixture": 21,
					"date": "18/2/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": 6,
					"guestGoals": 0,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 406010049,
					"fixture": 21,
					"date": "19/2/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": 0,
					"guestGoals": 6,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 804707995,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "20:00",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": 0,
					"guestGoals": 1,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 252752580,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": 1,
					"guestGoals": 1,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 508795968,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": 5,
					"guestGoals": 3,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 875575056,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": 6,
					"guestGoals": 3,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 914220757,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": 0,
					"guestGoals": 0,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 639246121,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": 6,
					"guestGoals": 0,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 613457411,
					"fixture": 22,
					"date": "24/2/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": 1,
					"guestGoals": 6,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 882027425,
					"fixture": 22,
					"date": "26/2/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": 1,
					"guestGoals": 5,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 89124643,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 874009761,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 799541510,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 872040377,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 678088476,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 788285283,
					"fixture": 23,
					"date": "3/3/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 388600445,
					"fixture": 23,
					"date": "2/3/2017",
					"time": "21:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 72448924,
					"fixture": 23,
					"date": "5/3/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 472726354,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 54556468,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 162846745,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 367480280,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 236146218,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 482915697,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 367760299,
					"fixture": 24,
					"date": "10/3/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 151584380,
					"fixture": 24,
					"date": "12/3/2017",
					"time": "20:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 349064095,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 512930556,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 970958519,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 989910020,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 584168417,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 996467502,
					"fixture": 25,
					"date": "17/3/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 735203644,
					"fixture": 25,
					"date": "18/3/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 55058094,
					"fixture": 25,
					"date": "19/3/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 507442546,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 275667625,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "20:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 874528384,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 885160888,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 382533023,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 818224758,
					"fixture": 26,
					"date": "24/3/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 127785275,
					"fixture": 26,
					"date": "25/3/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 858233945,
					"fixture": 26,
					"date": "26/3/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 969526123,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "20:30",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 743893340,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 488274794,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 503618863,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 198902257,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 453107333,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 276596767,
					"fixture": 27,
					"date": "31/3/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				},
				{
					"id_game": 778777096,
					"fixture": 27,
					"date": "2/4/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 17375530,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "20:30",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 883454271,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 433471051,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 553528317,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 922849835,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "21:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 716396064,
					"fixture": 28,
					"date": "7/4/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 42388097,
					"fixture": 28,
					"date": "8/4/2017",
					"time": "20:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 773471709,
					"fixture": 28,
					"date": "9/4/2017",
					"time": "16:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 30216756,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "20:00",
					"id_host": "udlp@reg-pref",
					"host": "U.D. Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Huracán",
					"id_guest": "adhuracan@reg-pref",
					"id_location": "loc-1",
					"pitch": "Anexo G.C."
				},
				{
					"id_game": 702523786,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "21:00",
					"id_host": "cddoramas@reg-pref",
					"host": "C.D. Doramas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.F. Unión Viera",
					"id_guest": "cfunionviera@reg-pref",
					"id_location": "loc-10",
					"pitch": "Cruce Arinaga"
				},
				{
					"id_game": 438201207,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "21:00",
					"id_host": "arucascf@reg-pref",
					"host": "Arucas C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Faycán",
					"id_guest": "cdfaycan@reg-pref",
					"id_location": "loc-11",
					"pitch": "Tonono"
				},
				{
					"id_game": 932157852,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "21:00",
					"id_host": "cdmaspalomas@reg-pref",
					"host": "C.D. Maspalomas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "A.D. Claret",
					"id_guest": "adclaret@reg-pref",
					"id_location": "loc-12",
					"pitch": "Maspalomas"
				},
				{
					"id_game": 948091669,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "21:00",
					"id_host": "udvalsequillo@reg-pref",
					"host": "U.D. Valsequillo",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.E.F. Puertos Las Palmas",
					"id_guest": "cefpuertoslp@reg-pref",
					"id_location": "loc-15",
					"pitch": "Valsequillo"
				},
				{
					"id_game": 182836901,
					"fixture": 29,
					"date": "21/4/2017",
					"time": "21:00",
					"id_host": "udteror@reg-pref",
					"host": "U.D. Teror",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Arguineguín",
					"id_guest": "cdarguineguin@reg-pref",
					"id_location": "loc-14",
					"pitch": "El Pino"
				},
				{
					"id_game": 648805062,
					"fixture": 29,
					"date": "22/4/2017",
					"time": "19:00",
					"id_host": "rcvictoria@reg-pref",
					"host": "R.C. Victoria",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Acodetti C.F.",
					"id_guest": "acodetticf@reg-pref",
					"id_location": "loc-13",
					"pitch": "Jorge Pulido"
				},
				{
					"id_game": 33869452,
					"fixture": 29,
					"date": "23/4/2017",
					"time": "11:30",
					"id_host": "cdcarnevali@reg-pref",
					"host": "C.D. Carnevali",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Telde",
					"id_guest": "udtelde@reg-pref",
					"id_location": "loc-16",
					"pitch": "La Mayordomia 2"
				},
				{
					"id_game": 349593097,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "cdfaycan@reg-pref",
					"host": "C.D. Faycán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Maspalomas",
					"id_guest": "cdmaspalomas@reg-pref",
					"id_location": "loc-2",
					"pitch": "Manuel Martín "
				},
				{
					"id_game": 388718023,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "cefpuertoslp@reg-pref",
					"host": "C.E.F. Puertos Las Palmas",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Teror",
					"id_guest": "udteror@reg-pref",
					"id_location": "loc-3",
					"pitch": "Junta de Obras"
				},
				{
					"id_game": 409508005,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "cdarguineguin@reg-pref",
					"host": "C.D. Arguineguín",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "R.C. Victoria",
					"id_guest": "rcvictoria@reg-pref",
					"id_location": "loc-9",
					"pitch": "Arguineguín"
				},
				{
					"id_game": 674964409,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "adclaret@reg-pref",
					"host": "A.D. Claret",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Doramas",
					"id_guest": "cddoramas@reg-pref",
					"id_location": "loc-4",
					"pitch": "Colegio Claret"
				},
				{
					"id_game": 62007466,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "20:00",
					"id_host": "adhuracan@reg-pref",
					"host": "A.D. Huracán",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "C.D. Carnevali",
					"id_guest": "cdcarnevali@reg-pref",
					"id_location": "loc-5",
					"pitch": "Pepe Gonçalves"
				},
				{
					"id_game": 390081113,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "cfunionviera@reg-pref",
					"host": "C.F. Unión Viera",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Valsequillo",
					"id_guest": "udvalsequillo@reg-pref",
					"id_location": "loc-8",
					"pitch": "Alfonso Silva"
				},
				{
					"id_game": 395221656,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "udtelde@reg-pref",
					"host": "U.D. Telde",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "Arucas C.F.",
					"id_guest": "arucascf@reg-pref",
					"id_location": "loc-7",
					"pitch": "Pablo Hernández"
				},
				{
					"id_game": 986405317,
					"fixture": 30,
					"date": "5/5/2017",
					"time": "21:00",
					"id_host": "acodetticf@reg-pref",
					"host": "Acodetti C.F.",
					"hostGoals": null,
					"guestGoals": null,
					"guest": "U.D. Las Palmas",
					"id_guest": "udlp@reg-pref",
					"id_location": "loc-6",
					"pitch": "La Mayordomia 1"
				}
			]
		}
	}


}